# Generated by Django 4.2.5 on 2023-10-11 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoExames',
            new_name='PedidoExame',
        ),
        migrations.RenameModel(
            old_name='SolicitacaoEsxames',
            new_name='SolicitacaoExame',
        ),
        migrations.RenameModel(
            old_name='TiposExames',
            new_name='TiposExame',
        ),
    ]
